name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254839084318:role/ECR
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag image
        run: |
          docker tag my-app:latest 254839084318.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

      - name: Push to ECR
        run: |
          docker push 254839084318.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
